name: pasajero_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Backend)
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3

  # Mapas (OSM Gratuito)
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # GPS y lÃ³gica
  geolocator: ^14.0.2
  http: ^1.5.0

  # ðŸ”” Notificaciones y voz (para alertas inteligentes)
  flutter_local_notifications: ^17.2.0
  flutter_tts: ^3.8.5

  # UI y animaciones
  cupertino_icons: ^1.0.8
  rive: ^0.13.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/4667-9425-isomatric-city.riv
